### ISSUE TITLE
plugin manufacturer name change

### ISSUE THREAD

**Issue by trummerschlunk** [trummerschlunk/master_me#69]
In the installer and as plugin manufacturer please write 'Klaus Scheuermann' instead of '4ohm'

**Comment by falkTX** [comment]
Might be fixed on 4965276dbd336adf2ae53e281d6eb944bb095e67

What part of the installer do you refer to?
I think the macOS one just uses a generic DPF one. But we can write a custom txt file for the description there.

**Comment by trummerschlunk** [comment]
Thanks. Seems to be fine now. If you could put a text in the macOS installer, it would be:

_Master_me is a multi platform, free and open source audio plug-in which optimizes sound in live streaming situations. Introducing no latency, it takes care of master levels and ‘polishes’ the sound with a chain of effects, closely modeled after the audio chain of Klaus Scheuermann’s mastering studio in Berlin, Germany.

Made with FAUST and DPF._

**Comment by falkTX** [comment]
Done in b388e90dcc0595daf9bb18315bb02476e14cdca0 does it look good?

<img width="622" alt="image" src="https://user-images.githubusercontent.com/1334853/187361336-9fcebe09-5731-43bb-9cec-6a40883c8e8d.png">

**Comment by falkTX** [comment]
Contents come from https://github.com/trummerschlunk/master_me/blob/master/plugin/macos-installer-welcome.txt so you can directly change that without needing to ask me.
The CI/actions will take care to generate new installers.

**Comment by trummerschlunk** [comment]
Nice, thank you!

**Comment by trummerschlunk** [comment]
the latest vst on mac still shows '4ohm' as vendor in Reaper...

**Comment by falkTX** [comment]
can you try a full rescan?

**Comment by trummerschlunk** [comment]
Ah, it came when loading an older project.
When I load the plugin freshly, it's fine :)
